POST http://localhost:5001/sociiinvest/europe-west2/generateToken
content-type: application/json

{
    "data": {"username": "peterferguson"}
}

### 
POST http://localhost:5001/sociiinvest/europe-west2/generateToken
content-type: application/json

{
    "data": {"username": "nicholasjames"}
}

### 