POST http://localhost:5001/sociiinvest/europe-west2/tradeSubmission
content-type: application/json

[
    {
        "groupRef": "groups/JPT",
        "assetRef": "tickers/US88160R1014",
        "executionCurrency": "GBP",
        "orderType": "BUY",
        "price": 420.00,
        "shares": 1,
        "messageId": "0a2b5cb0-635a-4d93-a097-79c73a79f9eb"
    },
    {
        "auth": {
            "uid": "7FhfstBEztYtVPDgkbmkuM0yo182"
        }
    }
]

