/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineResponse2004 {
  "accountId"?: string
  "accountNumber"?: string
  "statusFrom"?: string
  "statusTo"?: string
  "reason"?: string
  "at"?: Date

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "accountId",
      baseName: "account_id",
      type: "string",
      format: "uuid",
    },
    {
      name: "accountNumber",
      baseName: "account_number",
      type: "string",
      format: "",
    },
    {
      name: "statusFrom",
      baseName: "status_from",
      type: "string",
      format: "",
    },
    {
      name: "statusTo",
      baseName: "status_to",
      type: "string",
      format: "",
    },
    {
      name: "reason",
      baseName: "reason",
      type: "string",
      format: "",
    },
    {
      name: "at",
      baseName: "at",
      type: "Date",
      format: "date-time",
    },
  ]

  static getAttributeTypeMap() {
    return InlineResponse2004.attributeTypeMap
  }

  static from(json) {
    // - convert baseName to name
    if (json) {
      for (const { baseName, name } of this.attributeTypeMap) {
        if (baseName !== name && !(name in json)) {
          Object.assign(json, { [name]: json[baseName] })
          delete json[baseName]
        }
      }
    }
    return Object.assign(new this(), json)
  }

  public constructor() {}
}
