/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineObject {
  /**
   * OAuth client ID
   */
  "clientId"?: string
  /**
   * OAuth client secret
   */
  "clientSecret"?: string
  /**
   * redirect URI for the OAuth flow
   */
  "redirectUri"?: string
  /**
   * scopes requested by the OAuth flow
   */
  "scope"?: string
  /**
   * end-user account ID
   */
  "accountId"?: string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "clientId",
      baseName: "client_id",
      type: "string",
      format: "",
    },
    {
      name: "clientSecret",
      baseName: "client_secret",
      type: "string",
      format: "",
    },
    {
      name: "redirectUri",
      baseName: "redirect_uri",
      type: "string",
      format: "",
    },
    {
      name: "scope",
      baseName: "scope",
      type: "string",
      format: "",
    },
    {
      name: "accountId",
      baseName: "account_id",
      type: "string",
      format: "uuid",
    },
  ]

  static getAttributeTypeMap() {
    return InlineObject.attributeTypeMap
  }

  static from(json) {
    // - convert baseName to name
    for (const { baseName, name } of this.attributeTypeMap) {
      if (baseName !== name) {
        Object.assign(json, { [name]: json[baseName] })
        delete json[baseName]
      }
    }
    return Object.assign(new this(), json)
  }

  public constructor() {}
}
