/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class MarketDay {
  "date": string
  "open": string
  "close": string
  "sessionOpen"?: string
  "sessionClose"?: string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "date",
      baseName: "date",
      type: "string",
      format: "",
    },
    {
      name: "open",
      baseName: "open",
      type: "string",
      format: "",
    },
    {
      name: "close",
      baseName: "close",
      type: "string",
      format: "",
    },
    {
      name: "sessionOpen",
      baseName: "session_open",
      type: "string",
      format: "",
    },
    {
      name: "sessionClose",
      baseName: "session_close",
      type: "string",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return MarketDay.attributeTypeMap
  }
  static from(json) {
    // - convert baseName to name
    if (json) {
      for (const { baseName, name } of this.attributeTypeMap) {
        if (baseName !== name && !(name in json)) {
          Object.assign(json, { [name]: json[baseName] })
          delete json[baseName]
        }
      }
    }
    return Object.assign(new this(), json)
  }

  public constructor() {}
}
