/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Hold information about the result of KYC.
 */
export class KycResult {
  "reject"?: any
  "accept"?: any
  "indeterminate"?: any
  "addidionalInformation"?: string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "reject",
      baseName: "reject",
      type: "any",
      format: "",
    },
    {
      name: "accept",
      baseName: "accept",
      type: "any",
      format: "",
    },
    {
      name: "indeterminate",
      baseName: "indeterminate",
      type: "any",
      format: "",
    },
    {
      name: "addidionalInformation",
      baseName: "addidional_information",
      type: "string",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return KycResult.attributeTypeMap
  }

  static from(json) {
    // - convert baseName to name
    if (json) {
      for (const { baseName, name } of this.attributeTypeMap) {
        if (baseName !== name && !(name in json)) {
          Object.assign(json, { [name]: json[baseName] })
          delete json[baseName]
        }
      }
    }
    return Object.assign(new this(), json)
  }

  public constructor() {}
}
