/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BatchJournalRequestEntries } from "./BatchJournalRequestEntries"

export class BatchJournalRequest {
  "entryType": BatchJournalRequestEntryTypeEnum
  "fromAccount": string
  "description"?: string
  "entries"?: Array<BatchJournalRequestEntries>

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "entryType",
      baseName: "entry_type",
      type: "BatchJournalRequestEntryTypeEnum",
      format: "",
    },
    {
      name: "fromAccount",
      baseName: "from_account",
      type: "string",
      format: "uuid",
    },
    {
      name: "description",
      baseName: "description",
      type: "string",
      format: "",
    },
    {
      name: "entries",
      baseName: "entries",
      type: "Array<BatchJournalRequestEntries>",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return BatchJournalRequest.attributeTypeMap
  }

  static from(json) {
    // - convert baseName to name
    if (json) {
      for (const { baseName, name } of this.attributeTypeMap) {
        if (baseName !== name && !(name in json)) {
          Object.assign(json, { [name]: json[baseName] })
          delete json[baseName]
        }
      }
    }
    return Object.assign(new this(), json)
  }

  public constructor() {}
}

export type BatchJournalRequestEntryTypeEnum = "JNLC"
