/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ClockResponse {
  "timestamp"?: string
  "isOpen"?: boolean
  "nextOpen"?: string
  "nextClose"?: string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "timestamp",
      baseName: "timestamp",
      type: "string",
      format: "",
    },
    {
      name: "isOpen",
      baseName: "is_open",
      type: "boolean",
      format: "",
    },
    {
      name: "nextOpen",
      baseName: "next_open",
      type: "string",
      format: "",
    },
    {
      name: "nextClose",
      baseName: "next_close",
      type: "string",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return ClockResponse.attributeTypeMap
  }

  static from(json) {
    // - convert baseName to name
    if (json) {
      for (const { baseName, name } of this.attributeTypeMap) {
        if (baseName !== name && !(name in json)) {
          Object.assign(json, { [name]: json[baseName] })
          delete json[baseName]
        }
      }
    }
    return Object.assign(new this(), json)
  }

  public constructor() {}
}
