/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Position {
    'assetId'?: string;
    'symbol'?: string;
    'exchange'?: string;
    'assetClass'?: string;
    'avgEntryPrice'?: string;
    'qty'?: string;
    'side'?: string;
    'marketValue'?: string;
    'costBasis'?: string;
    'unrealizedPl'?: string;
    'unrealizedPlpc'?: string;
    'unrealizedIntradayPl'?: string;
    'unrealizedIntradayPlpc'?: string;
    'currentPrice'?: string;
    'lastdayPrice'?: string;
    'changeToday'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "assetId",
            "baseName": "asset_id",
            "type": "string"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string"
        },
        {
            "name": "exchange",
            "baseName": "exchange",
            "type": "string"
        },
        {
            "name": "assetClass",
            "baseName": "asset_class",
            "type": "string"
        },
        {
            "name": "avgEntryPrice",
            "baseName": "avg_entry_price",
            "type": "string"
        },
        {
            "name": "qty",
            "baseName": "qty",
            "type": "string"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "string"
        },
        {
            "name": "marketValue",
            "baseName": "market_value",
            "type": "string"
        },
        {
            "name": "costBasis",
            "baseName": "cost_basis",
            "type": "string"
        },
        {
            "name": "unrealizedPl",
            "baseName": "unrealized_pl",
            "type": "string"
        },
        {
            "name": "unrealizedPlpc",
            "baseName": "unrealized_plpc",
            "type": "string"
        },
        {
            "name": "unrealizedIntradayPl",
            "baseName": "unrealized_intraday_pl",
            "type": "string"
        },
        {
            "name": "unrealizedIntradayPlpc",
            "baseName": "unrealized_intraday_plpc",
            "type": "string"
        },
        {
            "name": "currentPrice",
            "baseName": "current_price",
            "type": "string"
        },
        {
            "name": "lastdayPrice",
            "baseName": "lastday_price",
            "type": "string"
        },
        {
            "name": "changeToday",
            "baseName": "change_today",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Position.attributeTypeMap;
    }
}

