# ! Should Fail

GET http://localhost:5001/sociiinvest/europe-west2/investCommand

###
POST http://localhost:5001/sociiinvest/europe-west2/investCommand
content-type: application/json

{ 
   "message":{ 
      "id":"", 
      "text":"/invest buy TSLA", 
      "command": "invest", 
      "args": "buy TSLA", 
      "html":"", 
      "type":"ephemeral", 
      "attachments":[], 
      "latest_reactions":[], 
      "own_reactions":[], 
      "reaction_counts":null, 
      "reaction_scores":null, 
      "reply_count":0, 
      "mentioned_users":[], 
      "silent":false 
   }, 
   "user":{ 
     "id":"peterferguson", 
     "role":"user", 
     "banned":false, 
     "online":true 
   }, 
   "form_data":{} 
}
###
POST http://localhost:5001/sociiinvest/europe-west2/investCommand
content-type: application/json

{ 
   "message":{ 
      "id":"", 
      "text":"/invest buy AAPL", 
      "command": "invest", 
      "args": "buy AAPL", 
      "html":"",
      "attachments":[],
      "mentioned_users":[]
   }, 
   "user":{ 
     "id":"peterferguson", 
     "role":"user", 
     "banned":false, 
     "online":true 
   }, 
   "form_data":{} 
}
###
POST http://localhost:5001/sociiinvest/europe-west2/investCommand
content-type: application/json

{ 
   "message":{ 
      "id":"", 
      "text":"/buy TSLA", 
      "command": "buy", 
      "args": "buy TSLA", 
      "html":"",
      "attachments":[],
      "mentioned_users":[]
   }, 
   "user":{ 
     "id":"peterferguson", 
     "role":"user", 
     "banned":false, 
     "online":true 
   }, 
   "form_data":{} 
}
