# coding: utf-8

"""
    Alpaca Broker API

    Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.journals_api import JournalsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestJournalsApi(unittest.TestCase):
    """JournalsApi unit test stubs"""

    def setUp(self):
        self.api = JournalsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_journal(self):
        """Test case for delete_journal

        Cancel a pending journal.  # noqa: E501
        """
        pass

    def test_events_journals_status_get(self):
        """Test case for events_journals_status_get

        Subscribe to journal events (SSE).  # noqa: E501
        """
        pass

    def test_get_journals(self):
        """Test case for get_journals

        Return a list of requested journals.  # noqa: E501
        """
        pass

    def test_post_journals(self):
        """Test case for post_journals

        Request a journal.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
