# coding: utf-8

"""
    Alpaca Broker API

    Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import broker_client
from broker_client.api.o_auth_api import OAuthApi  # noqa: E501
from broker_client.rest import ApiException


class TestOAuthApi(unittest.TestCase):
    """OAuthApi unit test stubs"""

    def setUp(self):
        self.api = OAuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_oauth_authorize_post(self):
        """Test case for oauth_authorize_post

        Issue a code.  # noqa: E501
        """
        pass

    def test_oauth_clients_client_id_get(self):
        """Test case for oauth_clients_client_id_get

        Returns an OAuth client.  # noqa: E501
        """
        pass

    def test_oauth_token_post(self):
        """Test case for oauth_token_post

        Issue a token.  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
