# coding: utf-8

"""
    Alpaca Broker API

    Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.events_api import EventsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_events_accounts_status_get(self):
        """Test case for events_accounts_status_get

        Subscribe to account status events (SSE).  # noqa: E501
        """
        pass

    def test_events_journals_status_get(self):
        """Test case for events_journals_status_get

        Subscribe to journal events (SSE).  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
