# coding: utf-8

"""
    Alpaca Broker API

    Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.untyped_wire_transfer_data import UntypedWireTransferData  # noqa: E501
from swagger_client.rest import ApiException


class TestUntypedWireTransferData(unittest.TestCase):
    """UntypedWireTransferData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUntypedWireTransferData(self):
        """Test UntypedWireTransferData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.untyped_wire_transfer_data.UntypedWireTransferData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
