# coding: utf-8

"""
    Alpaca Broker API

    Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import broker_client
from broker_client.api.assets_api import AssetsApi  # noqa: E501
from broker_client.rest import ApiException


class TestAssetsApi(unittest.TestCase):
    """AssetsApi unit test stubs"""

    def setUp(self):
        self.api = AssetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assets_asset_id_get(self):
        """Test case for assets_asset_id_get

        Retrieve an asset by UUID  # noqa: E501
        """
        pass

    def test_assets_get(self):
        """Test case for assets_get

        Retrieve all assets  # noqa: E501
        """
        pass

    def test_assets_symbol_get(self):
        """Test case for assets_symbol_get

        Retrieve an asset by symbol  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
