# coding: utf-8

"""
    Alpaca Broker API

    Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import broker_client
from broker_client.api.portfolio_api import PortfolioApi  # noqa: E501
from broker_client.rest import ApiException


class TestPortfolioApi(unittest.TestCase):
    """PortfolioApi unit test stubs"""

    def setUp(self):
        self.api = PortfolioApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_portfolio_history(self):
        """Test case for get_portfolio_history

        Returns timeseries data about equity and profit/loss (P/L) of the account in requested timespan.  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
