# coding: utf-8

"""
    Alpaca Broker API

    Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.documents_api import DocumentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDocumentsApi(unittest.TestCase):
    """DocumentsApi unit test stubs"""

    def setUp(self):
        self.api = DocumentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accounts_account_id_documents_document_id_download_get(self):
        """Test case for accounts_account_id_documents_document_id_download_get

        Download a document file that belongs to an account.  # noqa: E501
        """
        pass

    def test_accounts_account_id_documents_get(self):
        """Test case for accounts_account_id_documents_get

        Return a list of account documents.  # noqa: E501
        """
        pass

    def test_documents_document_id_get(self):
        """Test case for documents_document_id_get

        Download a document file directly  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
