# coding: utf-8

"""
    Alpaca Broker API

    Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import broker_client
from broker_client.models.bank_data import BankData  # noqa: E501
from broker_client.rest import ApiException


class TestBankData(unittest.TestCase):
    """BankData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankData(self):
        """Test BankData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = broker_client.models.bank_data.BankData()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
