# coding: utf-8

"""
    Alpaca Broker API

    Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2006(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'event_id': 'int',
        'at': 'datetime',
        'journal_id': 'str',
        'status_from': 'str',
        'status_to': 'str'
    }

    attribute_map = {
        'event_id': 'event_id',
        'at': 'at',
        'journal_id': 'journal_id',
        'status_from': 'status_from',
        'status_to': 'status_to'
    }

    def __init__(self, event_id=None, at=None, journal_id=None, status_from=None, status_to=None):  # noqa: E501
        """InlineResponse2006 - a model defined in Swagger"""  # noqa: E501
        self._event_id = None
        self._at = None
        self._journal_id = None
        self._status_from = None
        self._status_to = None
        self.discriminator = None
        if event_id is not None:
            self.event_id = event_id
        if at is not None:
            self.at = at
        if journal_id is not None:
            self.journal_id = journal_id
        if status_from is not None:
            self.status_from = status_from
        if status_to is not None:
            self.status_to = status_to

    @property
    def event_id(self):
        """Gets the event_id of this InlineResponse2006.  # noqa: E501


        :return: The event_id of this InlineResponse2006.  # noqa: E501
        :rtype: int
        """
        return self._event_id

    @event_id.setter
    def event_id(self, event_id):
        """Sets the event_id of this InlineResponse2006.


        :param event_id: The event_id of this InlineResponse2006.  # noqa: E501
        :type: int
        """

        self._event_id = event_id

    @property
    def at(self):
        """Gets the at of this InlineResponse2006.  # noqa: E501


        :return: The at of this InlineResponse2006.  # noqa: E501
        :rtype: datetime
        """
        return self._at

    @at.setter
    def at(self, at):
        """Sets the at of this InlineResponse2006.


        :param at: The at of this InlineResponse2006.  # noqa: E501
        :type: datetime
        """

        self._at = at

    @property
    def journal_id(self):
        """Gets the journal_id of this InlineResponse2006.  # noqa: E501


        :return: The journal_id of this InlineResponse2006.  # noqa: E501
        :rtype: str
        """
        return self._journal_id

    @journal_id.setter
    def journal_id(self, journal_id):
        """Sets the journal_id of this InlineResponse2006.


        :param journal_id: The journal_id of this InlineResponse2006.  # noqa: E501
        :type: str
        """

        self._journal_id = journal_id

    @property
    def status_from(self):
        """Gets the status_from of this InlineResponse2006.  # noqa: E501


        :return: The status_from of this InlineResponse2006.  # noqa: E501
        :rtype: str
        """
        return self._status_from

    @status_from.setter
    def status_from(self, status_from):
        """Sets the status_from of this InlineResponse2006.


        :param status_from: The status_from of this InlineResponse2006.  # noqa: E501
        :type: str
        """

        self._status_from = status_from

    @property
    def status_to(self):
        """Gets the status_to of this InlineResponse2006.  # noqa: E501


        :return: The status_to of this InlineResponse2006.  # noqa: E501
        :rtype: str
        """
        return self._status_to

    @status_to.setter
    def status_to(self, status_to):
        """Sets the status_to of this InlineResponse2006.


        :param status_to: The status_to of this InlineResponse2006.  # noqa: E501
        :type: str
        """

        self._status_to = status_to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2006, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2006):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
