version: "3.8"

services:
  redis:
    image: redis:6-alpine

  api:
    build: .
    ports:
      - 5000:5000
    command: python main.py
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  # worker:
  #   build: .
  #   command: celery worker --app=worker.celery --loglevel=info --logfile=logs/celery.log
  #   volumes:
  #     - .:/app
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - api
  #     - redis

  # dashboard:
  #   build: .
  #   command: flower --app=worker.celery --port=5555 --broker=redis://redis:6379/0
  #   ports:
  #     - 5556:5555
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - api
  #     - redis
  #     - worker
