/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ACHRelationshipData,
    ACHRelationshipDataFromJSON,
    ACHRelationshipDataFromJSONTyped,
    ACHRelationshipDataToJSON,
    ACHRelationshipResourceAllOf,
    ACHRelationshipResourceAllOfFromJSON,
    ACHRelationshipResourceAllOfFromJSONTyped,
    ACHRelationshipResourceAllOfToJSON,
    IdentifiedResource,
    IdentifiedResourceFromJSON,
    IdentifiedResourceFromJSONTyped,
    IdentifiedResourceToJSON,
} from './';

/**
 * 
 * @export
 * @interface ACHRelationshipResource
 */
export interface ACHRelationshipResource {
    /**
     * 
     * @type {string}
     * @memberof ACHRelationshipResource
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof ACHRelationshipResource
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ACHRelationshipResource
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ACHRelationshipResource
     */
    accountOwnerName: string;
    /**
     * 
     * @type {string}
     * @memberof ACHRelationshipResource
     */
    bankAccountType: ACHRelationshipResourceBankAccountTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ACHRelationshipResource
     */
    bankAccountNumber: string;
    /**
     * 
     * @type {string}
     * @memberof ACHRelationshipResource
     */
    bankRoutingNumber: string;
    /**
     * 
     * @type {string}
     * @memberof ACHRelationshipResource
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof ACHRelationshipResource
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof ACHRelationshipResource
     */
    status: ACHRelationshipResourceStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum ACHRelationshipResourceBankAccountTypeEnum {
    Checking = 'CHECKING',
    Savings = 'SAVINGS'
}/**
* @export
* @enum {string}
*/
export enum ACHRelationshipResourceStatusEnum {
    Queued = 'QUEUED',
    Approved = 'APPROVED',
    Pending = 'PENDING',
    CancelRequested = 'CANCEL_REQUESTED'
}

export function ACHRelationshipResourceFromJSON(json: any): ACHRelationshipResource {
    return ACHRelationshipResourceFromJSONTyped(json, false);
}

export function ACHRelationshipResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ACHRelationshipResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'accountOwnerName': json['account_owner_name'],
        'bankAccountType': json['bank_account_type'],
        'bankAccountNumber': json['bank_account_number'],
        'bankRoutingNumber': json['bank_routing_number'],
        'nickname': !exists(json, 'nickname') ? undefined : json['nickname'],
        'accountId': json['account_id'],
        'status': json['status'],
    };
}

export function ACHRelationshipResourceToJSON(value?: ACHRelationshipResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
        'account_owner_name': value.accountOwnerName,
        'bank_account_type': value.bankAccountType,
        'bank_account_number': value.bankAccountNumber,
        'bank_routing_number': value.bankRoutingNumber,
        'nickname': value.nickname,
        'account_id': value.accountId,
        'status': value.status,
    };
}


