/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Agreement
 */
export interface Agreement {
    /**
     * - margin_agreement: Alpaca Margin Agreement
     * - account_agreement: Alpaca Account Agreement
     * - customer_agreement: Alpaca Customer Agreement
     * @type {string}
     * @memberof Agreement
     */
    agreement: AgreementAgreementEnum;
    /**
     * 
     * @type {string}
     * @memberof Agreement
     */
    signedAt: string;
    /**
     * 
     * @type {string}
     * @memberof Agreement
     */
    ipAddress: string;
}

/**
* @export
* @enum {string}
*/
export enum AgreementAgreementEnum {
    MarginAgreement = 'margin_agreement',
    AccountAgreement = 'account_agreement',
    CustomerAgreement = 'customer_agreement'
}

export function AgreementFromJSON(json: any): Agreement {
    return AgreementFromJSONTyped(json, false);
}

export function AgreementFromJSONTyped(json: any, ignoreDiscriminator: boolean): Agreement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'agreement': json['agreement'],
        'signedAt': json['signed_at'],
        'ipAddress': json['ip_address'],
    };
}

export function AgreementToJSON(value?: Agreement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'agreement': value.agreement,
        'signed_at': value.signedAt,
        'ip_address': value.ipAddress,
    };
}


