/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankResourceAllOf
 */
export interface BankResourceAllOf {
    /**
     * 
     * @type {string}
     * @memberof BankResourceAllOf
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof BankResourceAllOf
     */
    status: BankResourceAllOfStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum BankResourceAllOfStatusEnum {
    Queued = 'QUEUED',
    CancelRequested = 'CANCEL_REQUESTED',
    SentToClearing = 'SENT_TO_CLEARING',
    Approved = 'APPROVED',
    Canceled = 'CANCELED'
}

export function BankResourceAllOfFromJSON(json: any): BankResourceAllOf {
    return BankResourceAllOfFromJSONTyped(json, false);
}

export function BankResourceAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankResourceAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'status': json['status'],
    };
}

export function BankResourceAllOfToJSON(value?: BankResourceAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account_id': value.accountId,
        'status': value.status,
    };
}


