/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchJournalRequestEntries
 */
export interface BatchJournalRequestEntries {
    /**
     * 
     * @type {string}
     * @memberof BatchJournalRequestEntries
     */
    toAccount: string;
    /**
     * 
     * @type {string}
     * @memberof BatchJournalRequestEntries
     */
    amount: string;
}

export function BatchJournalRequestEntriesFromJSON(json: any): BatchJournalRequestEntries {
    return BatchJournalRequestEntriesFromJSONTyped(json, false);
}

export function BatchJournalRequestEntriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchJournalRequestEntries {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'toAccount': json['to_account'],
        'amount': json['amount'],
    };
}

export function BatchJournalRequestEntriesToJSON(value?: BatchJournalRequestEntries | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'to_account': value.toAccount,
        'amount': value.amount,
    };
}


