/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrderTakeProfit
 */
export interface CreateOrderTakeProfit {
    /**
     * 
     * @type {string}
     * @memberof CreateOrderTakeProfit
     */
    limitPrice?: string;
}

export function CreateOrderTakeProfitFromJSON(json: any): CreateOrderTakeProfit {
    return CreateOrderTakeProfitFromJSONTyped(json, false);
}

export function CreateOrderTakeProfitFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderTakeProfit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'limitPrice': !exists(json, 'limit_price') ? undefined : json['limit_price'],
    };
}

export function CreateOrderTakeProfitToJSON(value?: CreateOrderTakeProfit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'limit_price': value.limitPrice,
    };
}


