/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrderStopLoss
 */
export interface CreateOrderStopLoss {
    /**
     * 
     * @type {string}
     * @memberof CreateOrderStopLoss
     */
    stopPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderStopLoss
     */
    limitPrice?: string;
}

export function CreateOrderStopLossFromJSON(json: any): CreateOrderStopLoss {
    return CreateOrderStopLossFromJSONTyped(json, false);
}

export function CreateOrderStopLossFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderStopLoss {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stopPrice': !exists(json, 'stop_price') ? undefined : json['stop_price'],
        'limitPrice': !exists(json, 'limit_price') ? undefined : json['limit_price'],
    };
}

export function CreateOrderStopLossToJSON(value?: CreateOrderStopLoss | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stop_price': value.stopPrice,
        'limit_price': value.limitPrice,
    };
}


