/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdentifiedResource
 */
export interface IdentifiedResource {
    /**
     * 
     * @type {string}
     * @memberof IdentifiedResource
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof IdentifiedResource
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof IdentifiedResource
     */
    updatedAt: Date;
}

export function IdentifiedResourceFromJSON(json: any): IdentifiedResource {
    return IdentifiedResourceFromJSONTyped(json, false);
}

export function IdentifiedResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentifiedResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function IdentifiedResourceToJSON(value?: IdentifiedResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}


