/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2005
 */
export interface InlineResponse2005 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2005
     */
    eventId?: number;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2005
     */
    at?: Date;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005
     */
    journalId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005
     */
    statusFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2005
     */
    statusTo?: string;
}

export function InlineResponse2005FromJSON(json: any): InlineResponse2005 {
    return InlineResponse2005FromJSONTyped(json, false);
}

export function InlineResponse2005FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2005 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventId': !exists(json, 'event_id') ? undefined : json['event_id'],
        'at': !exists(json, 'at') ? undefined : (new Date(json['at'])),
        'journalId': !exists(json, 'journal_id') ? undefined : json['journal_id'],
        'statusFrom': !exists(json, 'status_from') ? undefined : json['status_from'],
        'statusTo': !exists(json, 'status_to') ? undefined : json['status_to'],
    };
}

export function InlineResponse2005ToJSON(value?: InlineResponse2005 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'event_id': value.eventId,
        'at': value.at === undefined ? undefined : (value.at.toISOString()),
        'journal_id': value.journalId,
        'status_from': value.statusFrom,
        'status_to': value.statusTo,
    };
}


