/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JournalJNLS
 */
export interface JournalJNLS {
    /**
     * journal ID
     * @type {string}
     * @memberof JournalJNLS
     */
    id: string;
    /**
     * JNLS (constant)
     * @type {string}
     * @memberof JournalJNLS
     */
    entryType: string;
    /**
     * account ID the shares go from
     * @type {string}
     * @memberof JournalJNLS
     */
    fromAccount: string;
    /**
     * account ID the shares go to
     * @type {string}
     * @memberof JournalJNLS
     */
    toAccount: string;
    /**
     * 
     * @type {Date}
     * @memberof JournalJNLS
     */
    settleDate: Date | null;
    /**
     * 
     * @type {string}
     * @memberof JournalJNLS
     */
    status?: JournalJNLSStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof JournalJNLS
     */
    symbol: string;
    /**
     * 
     * @type {string}
     * @memberof JournalJNLS
     */
    qty: string;
    /**
     * 
     * @type {string}
     * @memberof JournalJNLS
     */
    price: string;
}

/**
* @export
* @enum {string}
*/
export enum JournalJNLSStatusEnum {
    Pending = 'pending',
    Canceled = 'canceled',
    Executed = 'executed',
    Queued = 'queued',
    Rejected = 'rejected',
    Deleted = 'deleted'
}

export function JournalJNLSFromJSON(json: any): JournalJNLS {
    return JournalJNLSFromJSONTyped(json, false);
}

export function JournalJNLSFromJSONTyped(json: any, ignoreDiscriminator: boolean): JournalJNLS {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'entryType': json['entry_type'],
        'fromAccount': json['from_account'],
        'toAccount': json['to_account'],
        'settleDate': (json['settle_date'] === null ? null : new Date(json['settle_date'])),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'symbol': json['symbol'],
        'qty': json['qty'],
        'price': json['price'],
    };
}

export function JournalJNLSToJSON(value?: JournalJNLS | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'entry_type': value.entryType,
        'from_account': value.fromAccount,
        'to_account': value.toAccount,
        'settle_date': (value.settleDate === null ? null : value.settleDate.toISOString().substr(0,10)),
        'status': value.status,
        'symbol': value.symbol,
        'qty': value.qty,
        'price': value.price,
    };
}


