/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Hold information about the result of KYC.
 * @export
 * @interface KycResult
 */
export interface KycResult {
    /**
     * 
     * @type {object}
     * @memberof KycResult
     */
    reject?: object;
    /**
     * 
     * @type {object}
     * @memberof KycResult
     */
    accept?: object;
    /**
     * 
     * @type {object}
     * @memberof KycResult
     */
    indeterminate?: object;
    /**
     * 
     * @type {string}
     * @memberof KycResult
     */
    addidionalInformation?: string;
}

export function KycResultFromJSON(json: any): KycResult {
    return KycResultFromJSONTyped(json, false);
}

export function KycResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): KycResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reject': !exists(json, 'reject') ? undefined : json['reject'],
        'accept': !exists(json, 'accept') ? undefined : json['accept'],
        'indeterminate': !exists(json, 'indeterminate') ? undefined : json['indeterminate'],
        'addidionalInformation': !exists(json, 'addidional_information') ? undefined : json['addidional_information'],
    };
}

export function KycResultToJSON(value?: KycResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reject': value.reject,
        'accept': value.accept,
        'indeterminate': value.indeterminate,
        'addidional_information': value.addidionalInformation,
    };
}


