/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchOrder
 */
export interface PatchOrder {
    /**
     * 
     * @type {string}
     * @memberof PatchOrder
     */
    qty?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchOrder
     */
    timeInForce?: PatchOrderTimeInForceEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchOrder
     */
    limitPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchOrder
     */
    stopPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchOrder
     */
    trail?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchOrder
     */
    clientOrderId?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchOrder
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchOrder
     */
    updatedAt: Date;
}

/**
* @export
* @enum {string}
*/
export enum PatchOrderTimeInForceEnum {
    Day = 'day',
    Gtc = 'gtc',
    Opg = 'opg',
    Cls = 'cls',
    Ioc = 'ioc',
    Fok = 'fok'
}

export function PatchOrderFromJSON(json: any): PatchOrder {
    return PatchOrderFromJSONTyped(json, false);
}

export function PatchOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'qty': !exists(json, 'qty') ? undefined : json['qty'],
        'timeInForce': !exists(json, 'time_in_force') ? undefined : json['time_in_force'],
        'limitPrice': !exists(json, 'limit_price') ? undefined : json['limit_price'],
        'stopPrice': !exists(json, 'stop_price') ? undefined : json['stop_price'],
        'trail': !exists(json, 'trail') ? undefined : json['trail'],
        'clientOrderId': !exists(json, 'client_order_id') ? undefined : json['client_order_id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function PatchOrderToJSON(value?: PatchOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'qty': value.qty,
        'time_in_force': value.timeInForce,
        'limit_price': value.limitPrice,
        'stop_price': value.stopPrice,
        'trail': value.trail,
        'client_order_id': value.clientOrderId,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}


