/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountStatus } from "./AccountStatus"
import { Agreement } from "./Agreement"
import { ApplicationDocument } from "./ApplicationDocument"
import { Contact } from "./Contact"
import { Disclosures } from "./Disclosures"
import { Identity } from "./Identity"
import { KycResult } from "./KycResult"
import { TrustedContact } from "./TrustedContact"
import { HttpFile } from "../http/http"

export class AccountExtended {
  "id"?: string
  "accountNumber"?: string
  "status"?: AccountStatus
  /**
   * Always \"USD\"
   */
  "currency"?: string
  "createdAt"?: Date
  "lastEquity"?: string
  "kycResults"?: KycResult
  "contact"?: Contact
  "identity"?: Identity
  "disclosures"?: Disclosures
  /**
   * The client has to present Alpaca Account Agreement and Margin Agreement to the end user, and have them read full sentences.
   */
  "agreements"?: Array<Agreement>
  "documents"?: Array<ApplicationDocument>
  "trustedContact"?: TrustedContact

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
      format: "uuid",
    },
    {
      name: "accountNumber",
      baseName: "account_number",
      type: "string",
      format: "",
    },
    {
      name: "status",
      baseName: "status",
      type: "AccountStatus",
      format: "",
    },
    {
      name: "currency",
      baseName: "currency",
      type: "string",
      format: "",
    },
    {
      name: "createdAt",
      baseName: "created_at",
      type: "Date",
      format: "date-time",
    },
    {
      name: "lastEquity",
      baseName: "last_equity",
      type: "string",
      format: "decimal",
    },
    {
      name: "kycResults",
      baseName: "kyc_results",
      type: "KycResult",
      format: "",
    },
    {
      name: "contact",
      baseName: "contact",
      type: "Contact",
      format: "",
    },
    {
      name: "identity",
      baseName: "identity",
      type: "Identity",
      format: "",
    },
    {
      name: "disclosures",
      baseName: "disclosures",
      type: "Disclosures",
      format: "",
    },
    {
      name: "agreements",
      baseName: "agreements",
      type: "Array<Agreement>",
      format: "",
    },
    {
      name: "documents",
      baseName: "documents",
      type: "Array<ApplicationDocument>",
      format: "",
    },
    {
      name: "trustedContact",
      baseName: "trusted_contact",
      type: "TrustedContact",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return AccountExtended.attributeTypeMap
  }

  public constructor() {}
}
