/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActivityType } from "./ActivityType"
import { HttpFile } from "../http/http"

/**
 * Base for activity types
 */
export class Activity {
  "id"?: string
  "accountId"?: string
  "activityType"?: ActivityType

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
      format: "uuid",
    },
    {
      name: "accountId",
      baseName: "account_id",
      type: "string",
      format: "uuid",
    },
    {
      name: "activityType",
      baseName: "activity_type",
      type: "ActivityType",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return Activity.attributeTypeMap
  }

  public constructor() {}
}
