/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActivityType } from "./ActivityType"
import { NonTradeActivity } from "./NonTradeActivity"
import { TradeActivity } from "./TradeActivity"
import { HttpFile } from "../http/http"

export class ActivityItem {
  "id"?: string
  "accountId"?: string
  "activityType"?: ActivityType
  "transactionTime"?: string
  "type"?: ActivityItemTypeEnum
  "price"?: string
  "qty"?: string
  "side"?: ActivityItemSideEnum
  "symbol"?: string
  "leavesQty"?: string
  "orderId"?: string
  "cumQty"?: string
  "orderStatus"?: ActivityItemOrderStatusEnum
  "date"?: string
  "netAmount"?: string
  "description"?: string
  "status"?: ActivityItemStatusEnum
  "perShareAmount"?: string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
      format: "uuid",
    },
    {
      name: "accountId",
      baseName: "account_id",
      type: "string",
      format: "uuid",
    },
    {
      name: "activityType",
      baseName: "activity_type",
      type: "ActivityType",
      format: "",
    },
    {
      name: "transactionTime",
      baseName: "transaction_time",
      type: "string",
      format: "timestamp",
    },
    {
      name: "type",
      baseName: "type",
      type: "ActivityItemTypeEnum",
      format: "",
    },
    {
      name: "price",
      baseName: "price",
      type: "string",
      format: "",
    },
    {
      name: "qty",
      baseName: "qty",
      type: "string",
      format: "",
    },
    {
      name: "side",
      baseName: "side",
      type: "ActivityItemSideEnum",
      format: "",
    },
    {
      name: "symbol",
      baseName: "symbol",
      type: "string",
      format: "",
    },
    {
      name: "leavesQty",
      baseName: "leaves_qty",
      type: "string",
      format: "",
    },
    {
      name: "orderId",
      baseName: "order_id",
      type: "string",
      format: "uuid",
    },
    {
      name: "cumQty",
      baseName: "cum_qty",
      type: "string",
      format: "",
    },
    {
      name: "orderStatus",
      baseName: "order_status",
      type: "ActivityItemOrderStatusEnum",
      format: "",
    },
    {
      name: "date",
      baseName: "date",
      type: "string",
      format: "date",
    },
    {
      name: "netAmount",
      baseName: "net_amount",
      type: "string",
      format: "",
    },
    {
      name: "description",
      baseName: "description",
      type: "string",
      format: "",
    },
    {
      name: "status",
      baseName: "status",
      type: "ActivityItemStatusEnum",
      format: "",
    },
    {
      name: "perShareAmount",
      baseName: "per_share_amount",
      type: "string",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return ActivityItem.attributeTypeMap
  }

  static from(json) {
    // - convert baseName to name
    for (const { baseName, name } of this.attributeTypeMap) {
      if (baseName !== name) {
        Object.assign(json, { [name]: json[baseName] })
        delete json[baseName]
      }
    }
    return Object.assign(new this(), json)
  }

  public constructor() {}
}

export type ActivityItemTypeEnum = "fill" | "partial_fill"
export type ActivityItemSideEnum = "buy" | "sell"
export type ActivityItemOrderStatusEnum =
  | "new"
  | "partially_filled"
  | "filled"
  | "done_for_day"
  | "canceled"
  | "expired"
  | "replaced"
  | "pending_cancel"
  | "pending_replace"
  | "accepted"
  | "pending_new"
  | "accepted_for_bidding"
  | "stopped"
  | "rejected"
  | "suspended"
  | "calculated"
export type ActivityItemStatusEnum = "executed" | "correct" | "canceled"
