/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http"

export type ActivityType =
  | "FILL"
  | "ACATC"
  | "ACATS"
  | "CSD"
  | "CSR"
  | "CSW"
  | "DIV"
  | "DIVCGL"
  | "DIVCGS"
  | "DIVNRA"
  | "DIVROC"
  | "DIVTXEX"
  | "INT"
  | "JNLC"
  | "JNLS"
  | "MA"
  | "NC"
  | "PTC"
  | "REORG"
  | "SSO"
  | "SSP"
