/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http"

export class BankResourceAllOf {
  "accountId": string
  "status": BankResourceAllOfStatusEnum

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "accountId",
      baseName: "account_id",
      type: "string",
      format: "uuid",
    },
    {
      name: "status",
      baseName: "status",
      type: "BankResourceAllOfStatusEnum",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return BankResourceAllOf.attributeTypeMap
  }

  public constructor() {}
}

export type BankResourceAllOfStatusEnum =
  | "QUEUED"
  | "CANCEL_REQUESTED"
  | "SENT_TO_CLEARING"
  | "APPROVED"
  | "CANCELED"
