/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http"

/**
 * Contact is the model for the account owner contact information.
 */
export class Contact {
  "emailAddress"?: string
  /**
   * with country code, no hyphen or space
   */
  "phoneNumber"?: string
  "streetAddress"?: Array<string>
  "city"?: string
  "state"?: string
  "postalCode"?: string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "emailAddress",
      baseName: "email_address",
      type: "string",
      format: "email",
    },
    {
      name: "phoneNumber",
      baseName: "phone_number",
      type: "string",
      format: "",
    },
    {
      name: "streetAddress",
      baseName: "street_address",
      type: "Array<string>",
      format: "",
    },
    {
      name: "city",
      baseName: "city",
      type: "string",
      format: "",
    },
    {
      name: "state",
      baseName: "state",
      type: "string",
      format: "",
    },
    {
      name: "postalCode",
      baseName: "postal_code",
      type: "string",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return Contact.attributeTypeMap
  }

  static from(json) {
    // - convert baseName to name
    for (const { baseName, name } of this.attributeTypeMap) {
      if (baseName !== name) {
        Object.assign(json, { [name]: json[baseName] })
        delete json[baseName]
      }
    }
    return Object.assign(new this(), json)
  }

  public constructor() {}
}
