/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http"

/**
 * - identity_verification:   identity verification document - address_verification:   address verification document - date_of_birth_verification:   date of birth verification document - tax_id_verification:   tax ID verification document - account_approval_letter:   407 approval letter - cip_result:   initial CIP result
 */
export type DocumentType =
  | "identity_verification"
  | "address_verification"
  | "date_of_birth_verification"
  | "tax_id_verification"
  | "account_approval_letter"
  | "cip_result"
