/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http"

/**
 * Identity is the model to provide account owner’s identity information.
 */
export class Identity {
  "givenName": string
  "familyName": string
  "dateOfBirth": string
  "taxId"?: string
  "taxIdType"?: IdentityTaxIdTypeEnum
  /**
   * [ISO 3166-1 alpha-3](https://www.iso.org/iso-3166-country-codes.html).
   */
  "countryOfCitizenship"?: string
  /**
   * [ISO 3166-1 alpha-3](https://www.iso.org/iso-3166-country-codes.html).
   */
  "countryOfBirth"?: string
  /**
   * [ISO 3166-1 alpha-3](https://www.iso.org/iso-3166-country-codes.html).
   */
  "countryOfTaxResidence": string
  "fundingSource": Array<IdentityFundingSourceEnum>
  "annualIncomeMin"?: number
  "annualIncomeMax"?: number
  "liquidNetWorthMin"?: number
  "liquidNetWorthMax"?: number
  "totalNetWorthMin"?: number
  "totalNetWorthMax"?: number
  /**
   * any extra information used for KYC purposes
   */
  "extra"?: any

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "givenName",
      baseName: "given_name",
      type: "string",
      format: "",
    },
    {
      name: "familyName",
      baseName: "family_name",
      type: "string",
      format: "",
    },
    {
      name: "dateOfBirth",
      baseName: "date_of_birth",
      type: "string",
      format: "date",
    },
    {
      name: "taxId",
      baseName: "tax_id",
      type: "string",
      format: "",
    },
    {
      name: "taxIdType",
      baseName: "tax_id_type",
      type: "IdentityTaxIdTypeEnum",
      format: "",
    },
    {
      name: "countryOfCitizenship",
      baseName: "country_of_citizenship",
      type: "string",
      format: "",
    },
    {
      name: "countryOfBirth",
      baseName: "country_of_birth",
      type: "string",
      format: "",
    },
    {
      name: "countryOfTaxResidence",
      baseName: "country_of_tax_residence",
      type: "string",
      format: "",
    },
    {
      name: "fundingSource",
      baseName: "funding_source",
      type: "Array<IdentityFundingSourceEnum>",
      format: "",
    },
    {
      name: "annualIncomeMin",
      baseName: "annual_income_min",
      type: "number",
      format: "",
    },
    {
      name: "annualIncomeMax",
      baseName: "annual_income_max",
      type: "number",
      format: "",
    },
    {
      name: "liquidNetWorthMin",
      baseName: "liquid_net_worth_min",
      type: "number",
      format: "",
    },
    {
      name: "liquidNetWorthMax",
      baseName: "liquid_net_worth_max",
      type: "number",
      format: "",
    },
    {
      name: "totalNetWorthMin",
      baseName: "total_net_worth_min",
      type: "number",
      format: "",
    },
    {
      name: "totalNetWorthMax",
      baseName: "total_net_worth_max",
      type: "number",
      format: "",
    },
    {
      name: "extra",
      baseName: "extra",
      type: "any",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return Identity.attributeTypeMap
  }

  public constructor() {}
}

export type IdentityTaxIdTypeEnum =
  | "USA_SSN"
  | "AUS_TFN"
  | "AUS_ABN"
  | "DEU_TAX_ID"
  | "FRA_SPI"
  | "GBR_UTR"
  | "GBR_NINO"
  | "HUN_TIN"
  | "IND_PAN"
  | "ISR_TAX_ID"
  | "ITA_TAX_ID"
  | "JPN_TAX_ID"
  | "NLD_TIN"
  | "SGP_NRIC"
  | "SGP_FIN"
  | "SGP_ASGD"
  | "SGP_ITR"
  | "SWE_TAX_ID"
  | "NOT_SPECIFIED"
export type IdentityFundingSourceEnum =
  | "employment_income"
  | "investments"
  | "inheritance"
  | "business_income"
  | "savings"
  | "family"
