/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Activity } from "./Activity"
import { ActivityType } from "./ActivityType"
import { NonTradeActivityAllOf } from "./NonTradeActivityAllOf"
import { HttpFile } from "../http/http"

export class NonTradeActivity {
  "id"?: string
  "accountId"?: string
  "activityType"?: ActivityType
  "date"?: string
  "netAmount"?: string
  "description"?: string
  "status"?: NonTradeActivityStatusEnum
  "symbol"?: string
  "qty"?: string
  "perShareAmount"?: string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
      format: "uuid",
    },
    {
      name: "accountId",
      baseName: "account_id",
      type: "string",
      format: "uuid",
    },
    {
      name: "activityType",
      baseName: "activity_type",
      type: "ActivityType",
      format: "",
    },
    {
      name: "date",
      baseName: "date",
      type: "string",
      format: "date",
    },
    {
      name: "netAmount",
      baseName: "net_amount",
      type: "string",
      format: "",
    },
    {
      name: "description",
      baseName: "description",
      type: "string",
      format: "",
    },
    {
      name: "status",
      baseName: "status",
      type: "NonTradeActivityStatusEnum",
      format: "",
    },
    {
      name: "symbol",
      baseName: "symbol",
      type: "string",
      format: "",
    },
    {
      name: "qty",
      baseName: "qty",
      type: "string",
      format: "",
    },
    {
      name: "perShareAmount",
      baseName: "per_share_amount",
      type: "string",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return NonTradeActivity.attributeTypeMap
  }

  public constructor() {}
}

export type NonTradeActivityStatusEnum = "executed" | "correct" | "canceled"
