/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http"

export class OrderObject {
  "id"?: string
  "clientOrderId"?: string
  "createdAt"?: Date
  "updatedAt"?: Date
  "submittedAt"?: Date
  "filledAt"?: Date
  "expiredAt"?: Date
  "canceledAt"?: Date
  "failedAt"?: Date
  "replacedAt"?: Date
  "replacedBy"?: string
  "replaces"?: string
  "assetId"?: string
  "symbol"?: string
  "assetClass"?: string
  "notional"?: string
  "qty"?: string
  "filledQty"?: string
  "filledAvgPrice"?: string
  "orderClass"?: OrderObjectOrderClassEnum
  "orderType"?: OrderObjectOrderTypeEnum
  "type"?: OrderObjectTypeEnum
  "side"?: OrderObjectSideEnum
  "timeInForce"?: OrderObjectTimeInForceEnum
  "limitPrice"?: string
  "stopPrice"?: string
  "status"?: OrderObjectStatusEnum
  "extendedHours"?: boolean
  "legs"?: Array<OrderObject>
  "trailPrice"?: string
  "trailPercent"?: string
  "hwm"?: string
  "commission"?: string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
      format: "uuid",
    },
    {
      name: "clientOrderId",
      baseName: "client_order_id",
      type: "string",
      format: "",
    },
    {
      name: "createdAt",
      baseName: "created_at",
      type: "Date",
      format: "date-time",
    },
    {
      name: "updatedAt",
      baseName: "updated_at",
      type: "Date",
      format: "date-time",
    },
    {
      name: "submittedAt",
      baseName: "submitted_at",
      type: "Date",
      format: "date-time",
    },
    {
      name: "filledAt",
      baseName: "filled_at",
      type: "Date",
      format: "date-time",
    },
    {
      name: "expiredAt",
      baseName: "expired_at",
      type: "Date",
      format: "date-time",
    },
    {
      name: "canceledAt",
      baseName: "canceled_at",
      type: "Date",
      format: "date-time",
    },
    {
      name: "failedAt",
      baseName: "failed_at",
      type: "Date",
      format: "date-time",
    },
    {
      name: "replacedAt",
      baseName: "replaced_at",
      type: "Date",
      format: "date-time",
    },
    {
      name: "replacedBy",
      baseName: "replaced_by",
      type: "string",
      format: "uuid",
    },
    {
      name: "replaces",
      baseName: "replaces",
      type: "string",
      format: "uuid",
    },
    {
      name: "assetId",
      baseName: "asset_id",
      type: "string",
      format: "uuid",
    },
    {
      name: "symbol",
      baseName: "symbol",
      type: "string",
      format: "",
    },
    {
      name: "assetClass",
      baseName: "asset_class",
      type: "string",
      format: "",
    },
    {
      name: "notional",
      baseName: "notional",
      type: "string",
      format: "decimal",
    },
    {
      name: "qty",
      baseName: "qty",
      type: "string",
      format: "decimal",
    },
    {
      name: "filledQty",
      baseName: "filled_qty",
      type: "string",
      format: "decimal",
    },
    {
      name: "filledAvgPrice",
      baseName: "filled_avg_price",
      type: "string",
      format: "decimal",
    },
    {
      name: "orderClass",
      baseName: "order_class",
      type: "OrderObjectOrderClassEnum",
      format: "",
    },
    {
      name: "orderType",
      baseName: "order_type",
      type: "OrderObjectOrderTypeEnum",
      format: "",
    },
    {
      name: "type",
      baseName: "type",
      type: "OrderObjectTypeEnum",
      format: "",
    },
    {
      name: "side",
      baseName: "side",
      type: "OrderObjectSideEnum",
      format: "",
    },
    {
      name: "timeInForce",
      baseName: "time_in_force",
      type: "OrderObjectTimeInForceEnum",
      format: "",
    },
    {
      name: "limitPrice",
      baseName: "limit_price",
      type: "string",
      format: "decimal",
    },
    {
      name: "stopPrice",
      baseName: "stop_price",
      type: "string",
      format: "decimal",
    },
    {
      name: "status",
      baseName: "status",
      type: "OrderObjectStatusEnum",
      format: "",
    },
    {
      name: "extendedHours",
      baseName: "extended_hours",
      type: "boolean",
      format: "",
    },
    {
      name: "legs",
      baseName: "legs",
      type: "Array<OrderObject>",
      format: "",
    },
    {
      name: "trailPrice",
      baseName: "trail_price",
      type: "string",
      format: "decimal",
    },
    {
      name: "trailPercent",
      baseName: "trail_percent",
      type: "string",
      format: "decimal",
    },
    {
      name: "hwm",
      baseName: "hwm",
      type: "string",
      format: "decimal",
    },
    {
      name: "commission",
      baseName: "commission",
      type: "string",
      format: "decimal",
    },
  ]

  static getAttributeTypeMap() {
    return OrderObject.attributeTypeMap
  }

  public constructor() {}
}

export type OrderObjectOrderClassEnum = "simple" | "bracket" | "oco" | "oto"
export type OrderObjectOrderTypeEnum =
  | "market"
  | "limit"
  | "stop"
  | "stop_limit"
  | "trailing_stop"
export type OrderObjectTypeEnum =
  | "market"
  | "limit"
  | "stop"
  | "stop_limit"
  | "trailing_stop"
export type OrderObjectSideEnum = "buy" | "sell"
export type OrderObjectTimeInForceEnum = "day" | "gtc" | "opg" | "cls" | "ioc" | "fok"
export type OrderObjectStatusEnum =
  | "new"
  | "partially_filled"
  | "filled"
  | "done_for_day"
  | "canceled"
  | "expired"
  | "replaced"
  | "pending_cancel"
  | "pending_replace"
  | "accepted"
  | "pending_new"
  | "accepted_for_bidding"
  | "stopped"
  | "rejected"
  | "suspended"
  | "calculated"
