/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http"

export class PatchOrder {
  "qty"?: string
  "timeInForce"?: PatchOrderTimeInForceEnum
  "limitPrice"?: string
  "stopPrice"?: string
  "trail"?: string
  "clientOrderId"?: string
  "createdAt": Date
  "updatedAt": Date

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "qty",
      baseName: "qty",
      type: "string",
      format: "decimal",
    },
    {
      name: "timeInForce",
      baseName: "time_in_force",
      type: "PatchOrderTimeInForceEnum",
      format: "",
    },
    {
      name: "limitPrice",
      baseName: "limit_price",
      type: "string",
      format: "decimal",
    },
    {
      name: "stopPrice",
      baseName: "stop_price",
      type: "string",
      format: "decimal",
    },
    {
      name: "trail",
      baseName: "trail",
      type: "string",
      format: "decimal",
    },
    {
      name: "clientOrderId",
      baseName: "client_order_id",
      type: "string",
      format: "",
    },
    {
      name: "createdAt",
      baseName: "created_at",
      type: "Date",
      format: "date-time",
    },
    {
      name: "updatedAt",
      baseName: "updated_at",
      type: "Date",
      format: "date-time",
    },
  ]

  static getAttributeTypeMap() {
    return PatchOrder.attributeTypeMap
  }

  static from(json) {
    // - convert baseName to name
    for (const { baseName, name } of this.attributeTypeMap) {
      if (baseName !== name) {
        Object.assign(json, { [name]: json[baseName] })
        delete json[baseName]
      }
    }
    return Object.assign(new this(), json)
  }

  public constructor() {}
}

export type PatchOrderTimeInForceEnum = "day" | "gtc" | "opg" | "cls" | "ioc" | "fok"
