/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http"

export class UntypedTransferData {
  "amount": string
  "direction": UntypedTransferDataDirectionEnum

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: "amount",
      baseName: "amount",
      type: "string",
      format: "decimal",
    },
    {
      name: "direction",
      baseName: "direction",
      type: "UntypedTransferDataDirectionEnum",
      format: "",
    },
  ]

  static getAttributeTypeMap() {
    return UntypedTransferData.attributeTypeMap
  }

  public constructor() {}
}

export type UntypedTransferDataDirectionEnum = "INCOMING" | "OUTGOING"
