GET http://localhost:3000/api/alpaca/createAccount
content-type: application/json

{
  "contact": {
    "email_address": "peter@socii.com",
    "phone_number": "+447825501123",
    "street_address": ["30 Donnybrook St"],
    "city": "Belfast",
    "state": "",
    "postal_code": "BT97DD",
    "country": "GBR"
  },
  "identity": {
    "given_name": "Peter",
    "family_name": "Ferguson",
    "date_of_birth": "1995-01-07",
    "tax_id": "AA123456C",
    "tax_id_type": "GBR_NINO",
    "country_of_citizenship": "GBR",
    "country_of_birth": "GBR",
    "country_of_tax_residence": "GBR",
    "funding_source": ["employment_income"]
  },
  "disclosures": {
    "is_control_person": false,
    "is_affiliated_exchange_or_finra": false,
    "is_politically_exposed": false,
    "immediate_family_exposed": false
  },
  "agreements": [
    {
      "agreement": "margin_agreement",
      "signed_at": "2020-09-11T18:09:33Z",
      "ip_address": "185.13.21.99"
    },
    {
      "agreement": "account_agreement",
      "signed_at": "2020-09-11T18:13:44Z",
      "ip_address": "185.13.21.99"
    },
    {
      "agreement": "customer_agreement",
      "signed_at": "2020-09-11T18:13:44Z",
      "ip_address": "185.13.21.99"
    }
  ],
  "documents": [
    {
      "document_type": "cip_result",
      "content": "VGhlcmUgYXJlIG5vIHdpbGQgYWxwYWNhcy4=",
      "mime_type": "application/pdf"
    },
    {
      "document_type": "identity_verification",
      "document_sub_type": "passport",
      "content": "QWxwYWNhcyBjYW5ub3QgbGl2ZSBhbG9uZS4=",
      "mime_type": "image/jpeg"
    }
  ]
}