POST http://localhost:3000/api/alpaca/postOrder
content-type: application/json

{
  # Firm account id 
  "account_id": "933ab506-9e30-3001-8230-50dc4e12861c",
  "symbol": "AAPL",
  "qty": "2.5",
  "side": "buy",
  "type": "market",
  "time_in_force": "day",
  "commission": "0"
}

###

POST http://localhost:3000/api/alpaca/postOrder
content-type: application/json

{
  # John Doe account id
  "account_id": "41e6a3a4-724e-481b-a88d-7c8dfb9ee04e",
  "symbol": "AAPL",
  "qty": "2.5",
  "side": "buy",
  "type": "market",
  "time_in_force": "day",
  "commission": "0"
}