/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models"

export class ACHRelationshipResourceAllOf {
  "accountId": string
  "status": ACHRelationshipResourceAllOf.StatusEnum

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: "accountId",
      baseName: "account_id",
      type: "string",
    },
    {
      name: "status",
      baseName: "status",
      type: "ACHRelationshipResourceAllOf.StatusEnum",
    },
  ]

  static from(json) {
    // - convert baseName to name
    for (const { baseName, name } of this.attributeTypeMap) {
      if (baseName !== name) {
        Object.assign(json, { [name]: json[baseName] })
        delete json[baseName]
      }
    }
    return Object.assign(new this(), json)
  }

  static getAttributeTypeMap() {
    return ACHRelationshipResourceAllOf.attributeTypeMap
  }
}

export namespace ACHRelationshipResourceAllOf {
  export enum StatusEnum {
    Queued = <any>"QUEUED",
    Approved = <any>"APPROVED",
    Pending = <any>"PENDING",
    CancelRequested = <any>"CANCEL_REQUESTED",
  }
}
