/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models"

export class InlineResponse2002 {
  "timestamp"?: string
  "isOpen"?: boolean
  "nextOpen"?: string
  "nextClose"?: string

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: "timestamp",
      baseName: "timestamp",
      type: "string",
    },
    {
      name: "isOpen",
      baseName: "is_open",
      type: "boolean",
    },
    {
      name: "nextOpen",
      baseName: "next_open",
      type: "string",
    },
    {
      name: "nextClose",
      baseName: "next_close",
      type: "string",
    },
  ]

  static from(json) {
    // - convert baseName to name
    for (const { baseName, name } of this.attributeTypeMap) {
      if (baseName !== name) {
        Object.assign(json, { [name]: json[baseName] })
        delete json[baseName]
      }
    }
    return Object.assign(new this(), json)
  }

  static getAttributeTypeMap() {
    return InlineResponse2002.attributeTypeMap
  }
}
