/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Agreement,
    AgreementFromJSON,
    AgreementFromJSONTyped,
    AgreementToJSON,
    Contact,
    ContactFromJSON,
    ContactFromJSONTyped,
    ContactToJSON,
    Disclosures,
    DisclosuresFromJSON,
    DisclosuresFromJSONTyped,
    DisclosuresToJSON,
    DocumentUpload,
    DocumentUploadFromJSON,
    DocumentUploadFromJSONTyped,
    DocumentUploadToJSON,
    Identity,
    IdentityFromJSON,
    IdentityFromJSONTyped,
    IdentityToJSON,
    TrustedContact,
    TrustedContactFromJSON,
    TrustedContactFromJSONTyped,
    TrustedContactToJSON,
} from './';

/**
 * 
 * @export
 * @interface AccountCreationObject
 */
export interface AccountCreationObject {
    /**
     * 
     * @type {Contact}
     * @memberof AccountCreationObject
     */
    contact?: Contact;
    /**
     * 
     * @type {Identity}
     * @memberof AccountCreationObject
     */
    identity?: Identity;
    /**
     * 
     * @type {Disclosures}
     * @memberof AccountCreationObject
     */
    disclosures?: Disclosures;
    /**
     * The client has to present Alpaca Account Agreement and
     * Margin Agreement to the end user, and have them read
     * full sentences.
     * @type {Array<Agreement>}
     * @memberof AccountCreationObject
     */
    agreements?: Array<Agreement>;
    /**
     * 
     * @type {Array<DocumentUpload>}
     * @memberof AccountCreationObject
     */
    documents?: Array<DocumentUpload>;
    /**
     * 
     * @type {TrustedContact}
     * @memberof AccountCreationObject
     */
    trustedContact?: TrustedContact;
}

export function AccountCreationObjectFromJSON(json: any): AccountCreationObject {
    return AccountCreationObjectFromJSONTyped(json, false);
}

export function AccountCreationObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCreationObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contact': !exists(json, 'contact') ? undefined : ContactFromJSON(json['contact']),
        'identity': !exists(json, 'identity') ? undefined : IdentityFromJSON(json['identity']),
        'disclosures': !exists(json, 'disclosures') ? undefined : DisclosuresFromJSON(json['disclosures']),
        'agreements': !exists(json, 'agreements') ? undefined : ((json['agreements'] as Array<any>).map(AgreementFromJSON)),
        'documents': !exists(json, 'documents') ? undefined : ((json['documents'] as Array<any>).map(DocumentUploadFromJSON)),
        'trustedContact': !exists(json, 'trusted_contact') ? undefined : TrustedContactFromJSON(json['trusted_contact']),
    };
}

export function AccountCreationObjectToJSON(value?: AccountCreationObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contact': ContactToJSON(value.contact),
        'identity': IdentityToJSON(value.identity),
        'disclosures': DisclosuresToJSON(value.disclosures),
        'agreements': value.agreements === undefined ? undefined : ((value.agreements as Array<any>).map(AgreementToJSON)),
        'documents': value.documents === undefined ? undefined : ((value.documents as Array<any>).map(DocumentUploadToJSON)),
        'trusted_contact': TrustedContactToJSON(value.trustedContact),
    };
}


