/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DocumentType,
    DocumentTypeFromJSON,
    DocumentTypeFromJSONTyped,
    DocumentTypeToJSON,
} from './';

/**
 * If an account has documents on the application submission,
 * it has the ApplicationDocument model in exchange with
 * DocumentUpload.
 * @export
 * @interface ApplicationDocument
 */
export interface ApplicationDocument {
    /**
     * 
     * @type {string}
     * @memberof ApplicationDocument
     */
    id: string;
    /**
     * 
     * @type {DocumentType}
     * @memberof ApplicationDocument
     */
    documentType: DocumentType;
    /**
     * 
     * @type {string}
     * @memberof ApplicationDocument
     */
    documentSubType?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationDocument
     */
    mimeType: string;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationDocument
     */
    createdAt: Date;
}

export function ApplicationDocumentFromJSON(json: any): ApplicationDocument {
    return ApplicationDocumentFromJSONTyped(json, false);
}

export function ApplicationDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationDocument {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'documentType': DocumentTypeFromJSON(json['document_type']),
        'documentSubType': !exists(json, 'document_sub_type') ? undefined : json['document_sub_type'],
        'mimeType': json['mime_type'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ApplicationDocumentToJSON(value?: ApplicationDocument | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'document_type': DocumentTypeToJSON(value.documentType),
        'document_sub_type': value.documentSubType,
        'mime_type': value.mimeType,
        'created_at': (value.createdAt.toISOString()),
    };
}


