/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * OAuth client ID
     * @type {string}
     * @memberof InlineObject
     */
    clientId?: string;
    /**
     * OAuth client secret
     * @type {string}
     * @memberof InlineObject
     */
    clientSecret?: string;
    /**
     * redirect URI for the OAuth flow
     * @type {string}
     * @memberof InlineObject
     */
    redirectUri?: string;
    /**
     * scopes requested by the OAuth flow
     * @type {string}
     * @memberof InlineObject
     */
    scope?: string;
    /**
     * end-user account ID
     * @type {string}
     * @memberof InlineObject
     */
    accountId?: string;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return InlineObjectFromJSONTyped(json, false);
}

export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clientId': !exists(json, 'client_id') ? undefined : json['client_id'],
        'clientSecret': !exists(json, 'client_secret') ? undefined : json['client_secret'],
        'redirectUri': !exists(json, 'redirect_uri') ? undefined : json['redirect_uri'],
        'scope': !exists(json, 'scope') ? undefined : json['scope'],
        'accountId': !exists(json, 'account_id') ? undefined : json['account_id'],
    };
}

export function InlineObjectToJSON(value?: InlineObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'client_id': value.clientId,
        'client_secret': value.clientSecret,
        'redirect_uri': value.redirectUri,
        'scope': value.scope,
        'account_id': value.accountId,
    };
}


