/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    JournalJNLC,
    JournalJNLS,
    JournalJNLCFromJSONTyped,
    JournalJNLCToJSON,
    JournalJNLSFromJSONTyped,
    JournalJNLSToJSON,
} from './';

/**
 * @type JournalResource
 * 
 * @export
 */
export type JournalResource = { entryType: 'JNLC' } & JournalJNLC | { entryType: 'JNLS' } & JournalJNLS;

export function JournalResourceFromJSON(json: any): JournalResource {
    return JournalResourceFromJSONTyped(json, false);
}

export function JournalResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): JournalResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['entryType']) {
        case 'JNLC':
            return {...JournalJNLCFromJSONTyped(json, true), entryType: 'JNLC'};
        case 'JNLS':
            return {...JournalJNLSFromJSONTyped(json, true), entryType: 'JNLS'};
        default:
            throw new Error(`No variant of JournalResource exists with 'entryType=${json['entryType']}'`);
    }
}

export function JournalResourceToJSON(value?: JournalResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['entryType']) {
        case 'JNLC':
            return JournalJNLCToJSON(value);
        case 'JNLS':
            return JournalJNLSToJSON(value);
        default:
            throw new Error(`No variant of JournalResource exists with 'entryType=${value['entryType']}'`);
    }
}

