/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NonTradeActivityAllOf
 */
export interface NonTradeActivityAllOf {
    /**
     * 
     * @type {Date}
     * @memberof NonTradeActivityAllOf
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof NonTradeActivityAllOf
     */
    netAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof NonTradeActivityAllOf
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof NonTradeActivityAllOf
     */
    status?: NonTradeActivityAllOfStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof NonTradeActivityAllOf
     */
    symbol?: string;
    /**
     * 
     * @type {string}
     * @memberof NonTradeActivityAllOf
     */
    qty?: string;
    /**
     * 
     * @type {string}
     * @memberof NonTradeActivityAllOf
     */
    perShareAmount?: string;
}

/**
* @export
* @enum {string}
*/
export enum NonTradeActivityAllOfStatusEnum {
    Executed = 'executed',
    Correct = 'correct',
    Canceled = 'canceled'
}

export function NonTradeActivityAllOfFromJSON(json: any): NonTradeActivityAllOf {
    return NonTradeActivityAllOfFromJSONTyped(json, false);
}

export function NonTradeActivityAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): NonTradeActivityAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'netAmount': !exists(json, 'net_amount') ? undefined : json['net_amount'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'symbol': !exists(json, 'symbol') ? undefined : json['symbol'],
        'qty': !exists(json, 'qty') ? undefined : json['qty'],
        'perShareAmount': !exists(json, 'per_share_amount') ? undefined : json['per_share_amount'],
    };
}

export function NonTradeActivityAllOfToJSON(value?: NonTradeActivityAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date === undefined ? undefined : (value.date.toISOString().substr(0,10)),
        'net_amount': value.netAmount,
        'description': value.description,
        'status': value.status,
        'symbol': value.symbol,
        'qty': value.qty,
        'per_share_amount': value.perShareAmount,
    };
}


