/* tslint:disable */
/* eslint-disable */
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferDataAllOf
 */
export interface TransferDataAllOf {
    /**
     * 
     * @type {string}
     * @memberof TransferDataAllOf
     */
    transferType: TransferDataAllOfTransferTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TransferDataAllOf
     */
    timing?: TransferDataAllOfTimingEnum;
}

/**
* @export
* @enum {string}
*/
export enum TransferDataAllOfTransferTypeEnum {
    Ach = 'ach',
    Wire = 'wire'
}/**
* @export
* @enum {string}
*/
export enum TransferDataAllOfTimingEnum {
    Immediate = 'immediate'
}

export function TransferDataAllOfFromJSON(json: any): TransferDataAllOf {
    return TransferDataAllOfFromJSONTyped(json, false);
}

export function TransferDataAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferDataAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transferType': json['transfer_type'],
        'timing': !exists(json, 'timing') ? undefined : json['timing'],
    };
}

export function TransferDataAllOfToJSON(value?: TransferDataAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transfer_type': value.transferType,
        'timing': value.timing,
    };
}


