export const activityTypeMapping = {
  Trades: ["success"],
  Cash: ["ACATC", "ACATS", "CSD", "CSR", "CSW"],
  General: [
    "INT",
    "JNLC",
    "JNLS",
    "MA",
    "NC",
    "PTC",
    "REORG",
    "SSO",
    "SSP",
    "DIV",
    "DIVCGL",
    "DIVCGS",
    "DIVNRA",
    "DIVROC",
    "DIVTXEX",
  ],
}
