"use strict";
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InlineResponse2007 = void 0;
class InlineResponse2007 {
    "accessToken";
    /**
     * constant `Bearer`
     */
    "tokenType";
    /**
     * token's scope
     */
    "scope";
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            name: "accessToken",
            baseName: "access_token",
            type: "string",
            format: "",
        },
        {
            name: "tokenType",
            baseName: "token_type",
            type: "string",
            format: "",
        },
        {
            name: "scope",
            baseName: "scope",
            type: "string",
            format: "",
        },
    ];
    static getAttributeTypeMap() {
        return InlineResponse2007.attributeTypeMap;
    }
    static from(json) {
        // - convert baseName to name
        if (json) {
            for (const { baseName, name } of this.attributeTypeMap) {
                if (baseName !== name && !(name in json)) {
                    Object.assign(json, { [name]: json[baseName] });
                    delete json[baseName];
                }
            }
        }
        return Object.assign(new this(), json);
    }
    constructor() { }
}
exports.InlineResponse2007 = InlineResponse2007;
//# sourceMappingURL=InlineResponse2007.js.map