"use strict";
/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.JournalData = void 0;
class JournalData {
    "entryType";
    "fromAccount";
    "toAccount";
    /**
     * Required for JNLC. The dollar amount to move. It has to be a positive value.
     */
    "amount";
    /**
     * Required for JNLS.
     */
    "symbol";
    /**
     * Required for JNLS. The number of shares to move. It has to be a positive value.
     */
    "qty";
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            name: "entryType",
            baseName: "entry_type",
            type: "JournalDataEntryTypeEnum",
            format: "",
        },
        {
            name: "fromAccount",
            baseName: "from_account",
            type: "string",
            format: "uuid",
        },
        {
            name: "toAccount",
            baseName: "to_account",
            type: "string",
            format: "uuid",
        },
        {
            name: "amount",
            baseName: "amount",
            type: "string",
            format: "decimal",
        },
        {
            name: "symbol",
            baseName: "symbol",
            type: "string",
            format: "",
        },
        {
            name: "qty",
            baseName: "qty",
            type: "string",
            format: "decimal",
        },
    ];
    static getAttributeTypeMap() {
        return JournalData.attributeTypeMap;
    }
    static from(json) {
        // - convert baseName to name
        if (json) {
            for (const { baseName, name } of this.attributeTypeMap) {
                if (baseName !== name && !(name in json)) {
                    Object.assign(json, { [name]: json[baseName] });
                    delete json[baseName];
                }
            }
        }
        return Object.assign(new this(), json);
    }
    constructor() { }
}
exports.JournalData = JournalData;
//# sourceMappingURL=JournalData.js.map